name: tyr-media

networks:
  internet:
  tyr-media-internal:
    name: tyr-media-internal
    internal: true

services:
  tyr-media-gluetun:
    image: qmcgaw/gluetun
    container_name: tyr-media-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${GLUETUN_FOLDER}:/gluetun
      - ${VPN_WG_CONFIG}:/gluetun/wireguard/wg0.conf
    environment:
      - VPN_PORT_FORWARDING_PROVIDER=private internet access
      - VPN_PORT_FORWARDING_USERNAME=${PIA_USER}
      - VPN_PORT_FORWARDING_PASSWORD=${PIA_PASSWORD}
      - SERVER_NAMES=${VPN_SERVER}
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      #- VPN_SERVICE_PROVIDER=private internet access
      #- OPENVPN_USER=${PIA_USER}
      #- OPENVPN_PASSWORD=${PIA_PASSWORD}
      #- SERVER_REGIONS=Netherlands
      - HTTPPROXY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
    restart: unless-stopped
    networks:
      - tyr-media-internal
      - internet
    ports:
      - ${PROWLARR_PORT}:9696
      - ${SONARR_PORT}:8989
      - ${RADARR_PORT}:7878
      - ${QBITTORRENT_WEBUI_PORT}:8080
      - ${MYLARR_PORT}:8090
      - ${READARR_PORT}:8787
      - ${HTTP_PROXY_PORT}:8888/tcp # HTTP proxy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:8888 2>&1 | grep -q '400 Bad Request' || exit 1"]

  tyr-media-prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: tyr-media-prowlarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${PROWLARR_FOLDER}:/config
    restart: unless-stopped
    network_mode: service:tyr-media-gluetun
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9696 || exit 1"]

  tyr-media-flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: tyr-media-flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    restart: unless-stopped
    network_mode: service:tyr-media-gluetun
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8191 || exit 1"]

  tyr-media-sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: tyr-media-sonarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${SONARR_FOLDER}:/config
      - ${TV_SHOWS_FOLDER}:/tv
      - ${DOWNLOADS_FOLDER}:/downloads
    restart: unless-stopped
    network_mode: service:tyr-media-gluetun
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8989 || exit 1"]

  tyr-media-radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: tyr-media-radarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RADARR_FOLDER}:/config
      - ${MOVIES_FOLDER}:/movies
      - ${DOWNLOADS_FOLDER}:/downloads
    restart: unless-stopped
    network_mode: service:tyr-media-gluetun
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:7878 || exit 1"]

  tyr-media-mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: tyr-media-mylar3
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${MYLARR_FOLDER}:/config
      - ${COMICS_FOLDER}:/comics
      - ${DOWNLOADS_FOLDER}:/downloads
    restart: unless-stopped
    network_mode: service:tyr-media-gluetun
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8090 || exit 1"]

  tyr-media-readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: tyr-media-readarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${READARR_FOLDER}:/config
      - ${BOOKS_FOLDER}:/books
      - ${DOWNLOADS_FOLDER}:/downloads
    restart: unless-stopped
    network_mode: service:tyr-media-gluetun
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:7878 || exit 1"]

  tyr-media-qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: tyr-media-qbittorrent
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${QBITTORRENT_FOLDER}:/config
      - ${DOWNLOADS_FOLDER}:/downloads
    restart: unless-stopped
    network_mode: service:tyr-media-gluetun
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080 || exit 1"]

  tyr-media-jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: tyr-media-jellyfin
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${JELLYFIN_FOLDER}:/config
      - ${TV_SHOWS_FOLDER}:/data/tvshows
      - ${MOVIES_FOLDER}:/data/movies
      - ${DOWNLOADS_FOLDER}:/data/downloads
    ports:
      - ${JELLYFIN_PORT}:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      - tyr-media-internal
      - internet # we need it for Trakt.tv integration & etc.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8096 || exit 1"]

  tyr-media-jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: tyr-media-jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
    ports:
      - ${JELLYSEERR_PORT}:5055
    volumes:
      - ${JELLYSEERR_FOLDER}:/app/config
    restart: unless-stopped
    networks:
      - tyr-media-internal
      - internet # Needed for host access.
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:5055 || exit 1"]

  tyr-media-homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: tyr-media-homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOSTNAME}
      PUID: ${USER_ID}
      PGID: ${GROUP_ID}
    ports:
      - 80:3000
    volumes:
      - ${HOMEPAGE_FOLDER}:/app/config
    restart: unless-stopped
    networks:
      - tyr-media-internal
      - internet # Needed for host access.
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://127.0.0.1:3000 || exit 1"]

  tyr-media-kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: tyr-media-kavita
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${KAVITA_FOLDER}:/config
      - ${READS_FOLDER}:/data
    ports:
      - ${KAVITA_PORT}:5000
    restart: unless-stopped
    networks:
      - tyr-media-internal
      - internet # Needed for host access.
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:5000 || exit 1"]

  #nginx:
  #  image: lscr.io/linuxserver/nginx:latest
  #  container_name: nginx
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=Etc/UTC
  #  volumes:
  #    - ./reverse-proxy.conf:/config/nginx/site-confs/default.conf
  #  ports:
  #    - ${NGINX_PORT}:80
  #  restart: unless-stopped
