name: tyr-infra

networks:
  internet:
  tyr-administration-internal:
    name: tyr-administration-internal
    external: true
  tyr-infrastructure-internal:
    name: tyr-infrastructure-internal
    external: true
  tyr-proxy-internal:
    name: tyr-proxy-internal
    external: true

services:
  tyr-infra-doneman:
    image: ewancoder/doneman:latest
    container_name: tyr-infra-doneman
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    mem_limit: 100m
    mem_reservation: 75m

  tyr-infra-pgadmin:
    image: dpage/pgadmin4
    container_name: tyr-infra-pgadmin
    env_file: /mnt/data/pet/pgadmin/secrets.env
    volumes:
      - /mnt/data/pet/pgadmin/data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - tyr-administration-internal
      - tyr-proxy-internal
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost || exit 1"]

  tyr-infra-seq:
    image: datalust/seq
    container_name: tyr-infra-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_API_CANONICALURI=https://seq.typingrealm.com
    volumes:
      - /mnt/data/seq:/data
    restart: unless-stopped
    ports:
      - 5341:5341
    networks:
      - tyr-infrastructure-internal
      - tyr-proxy-internal
      - internet # For exposing ports to host.
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep /seqsvr/Seq | grep -v grep || exit 1"]

  tyr-infra-redisinsight:
    image: redis/redisinsight:latest
    container_name: tyr-infra-redisinsight
    volumes:
      - /mnt/data/pet/redisinsight:/data
    restart: unless-stopped
    networks:
      - tyr-administration-internal
      - tyr-proxy-internal
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://127.0.0.1:5540 || exit 1"]

