name: prod-tyr-infra

networks:
  typingrealm:
    name: typingrealm
    external: true
  tyr-proxy-internal:
    name: tyr-proxy-internal
    external: true

services:
  doneman:
    image: ewancoder/doneman:latest
    container_name: prod-tyr-infra-doneman
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    mem_limit: 100m
    mem_reservation: 20m

  typingrealm-caddy:
    image: caddy
    container_name: typingrealm-caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy/data:/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 100m
    networks:
      - typingrealm
      - tyr-proxy-internal
    healthcheck:
      test: wget --spider http://localhost/health || exit 1

