---

- Media:
    - Request something:
        icon: jellyseerr.png
        href: http://ivanpc.local:5055
        description: Jellyseerr

    - Watch something:
        icon: jellyfin.png
        href: http://ivanpc.local:8096
        description: Jellyfin

    - Read something:
        icon: kavita.png
        href: http://ivanpc.local:10888
        description: Kavita

    - Track it:
        icon: trakt.png
        href: https://trakt.tv
        description: trakt.tv

- Management (admin, qwerty):
    - Torrents:
        icon: qbittorrent.png
        href: http://ivanpc.local:8080
        description: qBitTorrent (admin - qwerty)

    - TV Shows Tracker:
        icon: sonarr.png
        href: http://ivanpc.local:8989
        description: Sonarr

    - Movies Tracker:
        icon: radarr.png
        href: http://ivanpc.local:7878
        description: Radarr

    - Comics Tracker:
        icon: mylar.png
        href: http://ivanpc.local:8090
        description: Mylarr

    - Books Tracker:
        icon: readarr.png
        href: http://ivanpc.local:8787
        description: Readarr

- Other:
    - Seq logs:
        icon: seq.png
        href: http://ivanpc.local:35555

    - Indexers setup:
        icon: prowlarr.png
        href: http://ivanpc.local:9696
        description: Prowlarr

    - Torrents without VPN:
        icon: qbittorrent.png
        href: http://ivanpc.local:8081
        description: qBitTorrent w/o VPN
