#!/bin/bash
ponymix --sink-input list > /tmp/temp.mypo

if [ "$1" == "" ]; then
    if ! [ "$(cat /tmp/temp.mypo)" == "" ]; then
        apps="$(cat /tmp/temp.mypo | awk '/sink/{getline;print $1}')"
        inds=$(cat /tmp/temp.mypo | grep 'sink-input' | awk '{print $2}' | sed 's/://')
        vols=$(cat /tmp/temp.mypo | grep 'Avg. Volume:' | awk '{print $3}' | sed 's/%//')
        echo $inds > /tmp/inds.mypo
        IFS=$'\r\n' GLOBIGNORE='*' :; app=($apps)
        IFS=$'\r\n' GLOBIGNORE='*' :; ind=($inds)
        IFS=$'\r\n' GLOBIGNORE='*' :; vol=($vols)
        for (( i = 0; i < ${#ind[@]}; i++ )); do
            if ! [ "${ind[$i]}" == "" ]; then
                wmiir create /rbar/Audio${ind[$i]} &
                wmiir xwrite /rbar/Audio${ind[$i]} colors $(cat /tmp/settings.wmii | sed -n "7{p;q}")
                wmiir xwrite /rbar/Audio${ind[$i]} label "${app[$i]}: ${vol[$i]}" &
            fi
        done
    else
        if [ -f /tmp/inds.mypo ]; then
            rm /tmp/inds.mypo
        fi
    fi

    current=$(wmiir ls /rbar | grep Audio | sed -e 's/Audio//g')
    for i in $current; do
        echo $i
        if [ "$(echo $inds | grep $i)" == "" ] && ! [ "$i" == "" ]; then
            wmiir rm /rbar/Audio$i
        fi
    done
else
    IFS=$'\r\n' GLOBIGNORE='*' :; app=($(cat /tmp/temp.mypo | awk '/sink/{getline;print $1}'))
    IFS=$'\r\n' GLOBIGNORE='*' :; vol=($(cat /tmp/temp.mypo | grep 'Avg. Volume:' | awk '{print $3}' | sed 's/%//'))
    wmiir xwrite /rbar/Audio$2 label "${app[$1]}: ${vol[$1]}" &
fi

rm /tmp/temp.mypo
