#!/bin/bash

#Per 2 seconds :)
bytes=2048

if [ -f /tmp/rx ] && [ -f /tmp/tx ]; then
    rx_old=$(cat /tmp/rx)
    tx_old=$(cat /tmp/tx)
else
    rx_old=0
    tx_old=0
fi
ifconfig | grep 'enp2s0\|wlan' -A 7 | grep 'RX packets' | awk '{print $5}' > /tmp/rx
ifconfig | grep 'enp2s0\|wlan' -A 7 | grep 'TX packets' | awk '{print $5}' > /tmp/tx

echo `cat /tmp/rx` `cat /tmp/tx` $rx_old $tx_old $bytes | awk '
{
    tx = int(($1 - $3) / $5);
    rx = int(($2 - $4) / $5);
    traffic = int(($1 + $2) / 1000000);
}
m = tx ~ /^.{,3}$/ {
    printf "%d ", tx;
} !m {
    printf "%.1fM ", tx/1000;
}
m = rx ~ /^.{,3}$/ {
    printf "%d ", rx;
} !m {
    printf "%.1fM ", rx/1000;
}
m = traffic ~ /^.{,3}$/ {
    printf "%.0fM", traffic;
} !m {
    printf "%.1fG", traffic;
}
'
