#!/bin/sh -f
# Configure wmii
wmiiscript=wmiirc # For wmii.sh
. wmii.sh
# Settings
python ~/.wmii-hg/settings.py > /tmp/settings.wmii
var(){
    cat /tmp/settings.wmii | sed -n "$1{p;q}"
}

# Configuration Variables
MODKEY=$(var 1)
UP=$(var 2)
DOWN=$(var 3)
LEFT=$(var 4)
RIGHT=$(var 5)

# Bars
noticetimeout=5
noticebar=/rbar/!notice

# Colors tuples: "<text> <background> <border>"
export WMII_NORMCOLORS=$(var 6)
export WMII_FOCUSCOLORS=$(var 7)
export WMII_TAGFOCUSCOLORS=$(var 8)

export WMII_FONT=$(var 9)
export WMII_TERM=$(var 10)

set -- $(echo $WMII_NORMCOLORS $WMII_FOCUSCOLORS)
echo colors $WMII_NORMCOLORS | wmiir create $noticebar

# Event processing
wi_events <<'!'
# Events
Event CreateTag
	echo colors "$WMII_NORMCOLORS$wi_newline" label "$@" | wmiir create "/lbar/$@"
Event DestroyTag
	wmiir remove "/lbar/$@"
Event FocusTag
	wmiir xwrite "/lbar/$@" colors "$WMII_TAGFOCUSCOLORS"
Event UnfocusTag
	wmiir xwrite "/lbar/$@" colors "$WMII_NORMCOLORS"
Event UrgentTag
	shift
	wmiir xwrite "/lbar/$@" label "*$@"
Event NotUrgentTag
	shift
	wmiir xwrite "/lbar/$@" label "$@"
Event LeftBarClick LeftBarDND
	shift
	wmiir xwrite /ctl view "$@"
Event Unresponsive
	{
		client=$1; shift
		msg="The following client is not responding. What would you like to do?$wi_newline"
		resp=$(wihack -transient $client \
			      xmessage -nearmouse -buttons Kill,Wait -print \
			      -fn "${WMII_FONT%%,*}" "$msg $(wmiir read /client/sel/label)")
		if [ "$resp" = Kill ]; then
			wmiir xwrite /client/$client/ctl slay &
		fi
	}&
Event Notice
	wmiir xwrite $noticebar $wi_arg
	kill $xpid 2>/dev/null # Let's hope this isn't reused...
	{ sleep $noticetimeout; wmiir xwrite $noticebar ' '; }&
	xpid = $!

# Menus
Menu Client-3-Close
	wmiir xwrite /client/$1/ctl kill
Menu Client-3-Kill
	wmiir xwrite /client/$1/ctl slay
Event ClientMouseDown
	wi_fnmenu Client $2 $1 &

Menu LBar-3-Delete
	tag=$1; clients=$(wmiir read "/tag/$tag/index" | awk '/[^#]/{print $2}')
	for c in $clients; do
		if [ "$tag" = "$(wmiir read /client/$c/tags)" ]
		then wmiir xwrite /client/$c/ctl kill
		else wmiir xwrite /client/$c/ctl tags -$tag
		fi
		[ "$tag" = "$(wi_seltag)" ] &&
			wmiir xwrite /ctl view $(wi_tags | wi_nexttag)
	done
Event LeftBarMouseDown
	wi_fnmenu LBar "$@" &

# Actions
Action showkeys
	echo "$KeysHelp" | xmessage -file - -fn ${WMII_FONT%%,*}
Action quit
	wmiir xwrite /ctl quit
Action exec
	wmiir xwrite /ctl exec "$@"
Action pywmii
    ~/.wmii-hg/wmii.py

# Key Bindings
KeyGroup Moving around
Key $MODKEY-$LEFT   # Select the client to the left
	wmiir xwrite /tag/sel/ctl select left
Key $MODKEY-$RIGHT  # Select the client to the right
	wmiir xwrite /tag/sel/ctl select right
Key $MODKEY-$UP     # Select the client above
	wmiir xwrite /tag/sel/ctl select up
Key $MODKEY-$DOWN   # Select the client below
	wmiir xwrite /tag/sel/ctl select down

KeyGroup Moving clients around
Key $MODKEY-Shift-$LEFT   # Move selected client to the left
	wmiir xwrite /tag/sel/ctl send sel left
Key $MODKEY-Shift-$RIGHT  # Move selected client to the right
	wmiir xwrite /tag/sel/ctl send sel right
Key $MODKEY-Shift-$UP     # Move selected client up
	wmiir xwrite /tag/sel/ctl send sel up
Key $MODKEY-Shift-$DOWN   # Move selected client down
	wmiir xwrite /tag/sel/ctl send sel down

KeyGroup Resizing clients
Key $MODKEY-Control-$LEFT
    wmiir xwrite /tag/sel/ctl grow sel sel right -2
Key $MODKEY-Control-$RIGHT
    wmiir xwrite /tag/sel/ctl grow sel sel right 2
Key $MODKEY-Control-$UP
    wmiir xwrite /tag/sel/ctl grow sel sel down -2
Key $MODKEY-Control-$DOWN
    wmiir xwrite /tag/sel/ctl grow sel sel down 2

KeyGroup Floating switching
Key $MODKEY-space   # Toggle between floating and managed layers
	wmiir xwrite /tag/sel/ctl select toggle
Key $MODKEY-Shift-space   # Toggle selected client between floating and managed layers
	wmiir xwrite /tag/sel/ctl send sel toggle

KeyGroup Client actions
Key $MODKEY-f # Toggle selected client's fullsceen state
	wmiir xwrite /client/sel/ctl Fullscreen toggle
Key $MODKEY-bracketright # Toggle urgent
    wmiir xwrite /client/sel/ctl urgent toggle
Key $MODKEY-q # Close client
    sc=$(wmiir read /client/sel/label)
    if [ "$sc" != "tilda" ]; then
        wmiir xwrite /client/sel/ctl kill
    fi
Key $MODKEY-Shift-q #Kill client
    sc=$(wmiir read /client/sel/label)
    if [ "$sc" != "tilda" ]; then
        wmiir xwrite /client/sel/ctl slay
    fi

KeyGroup Changing column modes
Key $MODKEY-d # Set column to default mode
	wmiir xwrite /tag/sel/ctl colmode sel default-max
Key $MODKEY-s # Set column to stack mode
	wmiir xwrite /tag/sel/ctl colmode sel stack-max
Key $MODKEY-m # Set column to max mode
	wmiir xwrite /tag/sel/ctl colmode sel stack+max

KeyGroup Running programs
Key $MODKEY-a   # Open wmii actions menu
	action $(wi_actions | wimenu -h "${hist}.actions" -n $histnum) &
Key $MODKEY-p   # Open dmenu programs menu
    echo "`wmiir ls /tag | sed '$d'`" > /tmp/tags.dm
    x=0
    while read line; do
        x=$(( $x + 6 * $(( ${#line} - 1 )) + 11 ))
    done < /tmp/tags.dm
    w=$(( 600 - $x ))
    ~/bin/dm -i -nb black -fn '-*-terminus-medium' -nf orange -sb black -p "#" -w $w -x $x &
Key $MODKEY-Return # Launch a terminal
	eval wmiir setsid $WMII_TERM &

KeyGroup Personal software
Key $MODKEY-c
	chromium &
Key $MODKEY-g
	gvim &
Key $MODKEY-r
    chromium coggle.it &
    
KeyGroup Volume control   
Key $MODKEY-w
    urxvt -e alsamixer &
Key $MODKEY-x
    if [ "`pactl list; echo $?`" == "1" ]; then
        if [ "`amixer -q sset Master 2+; echo $?`" == "1" ]; then
            amixer -q sset PCM 2+ &
        fi
    else
	    amixer -q sset Master 2500+ &
    fi
Key $MODKEY-z
    if [ "`pactl list; echo $?`" == "1" ]; then
        if [ "`amixer -q sset Master 2-; echo $?`" == "1" ]; then
            amixer -q sset PCM 2- &
        fi
    else
	    amixer -q sset Master 2500- &
    fi

KeyGroup Keyboard layouts
Key $MODKEY-i
    sed -i 's/ca(fr),ru/us,ru/g' ~/.config/gxkb/gxkb.cfg && killall gxkb && gxkb &
Key $MODKEY-Shift-i
    sed -i 's/us,ru/ca(fr),ru/g' ~/.config/gxkb/gxkb.cfg && killall gxkb && gxkb &

KeyGroup Others
#Google KEEP
Key $MODKEY-e
    chromium --app-id=hmjkmjkepdijhoojdojkdfohbdgmmhki &
#Turn off mouse
Key $MODKEY-v
    id=`xinput --list | grep "Wheel Mouse" | awk '{print $7}' | cut -f2 -d "="`
    if [ "`xinput --list-props $id | grep "Device Enabled" | awk '{print $4}'`" == "0" ]; then
        state=1
    else
        state=0
    fi
    xinput set-int-prop $id "Device Enabled" 8 $state
#Lock session (screensaver)
Key $MODKEY-KP_Enter
    slimlock
Key $MODKEY-Shift-KP_Enter
	wmiir xwrite /ctl quit
#Remove 'New messages' notification
Key $MODKEY-apostrophe
    wmiir remove /rbar/ZNotify
#System update
Key XF86WakeUp
    urxvt -e yaourt -Syua --noconfirm &
#Screenshot
Key XF86Sleep
    dbss &
#Go to RSS tag
Key XF86PowerOff
    if [ $cv == "" ]; then
        cv="1"
    fi
    seltag=$(wmiir read /tag/sel/ctl | sed 1q)
    if [ $seltag == "RSS" ]; then
        wmiir xwrite /ctl view $cv
    else
        cv=$seltag
        wmiir xwrite /ctl view RSS
    fi
Key $MODKEY-Shift-XF86PowerOff
    wmiir xwrite /rbar/\!notice colors "`cat /tmp/settings.wmii | sed -n '11p'`"
    wmiir xwrite /rbar/\!notice label "Power off..."
    baconf
    systemctl poweroff -i
Key $MODKEY-Shift-XF86WakeUp
    wmiir xwrite /rbar/\!notice colors "`cat /tmp/settings.wmii | sed -n '11p'`"
    wmiir xwrite /rbar/\!notice label "Reboot..."
    baconf
    systemctl reboot -i
#Change wallpaper
Key $MODKEY-XF86PowerOff
    feh --bg-fill --randomize --recursive Dropbox/Pictures
#Increase/decrease transparency of current window
Key $MODKEY-KP_Subtract
    transset-df -a --min 0.1 --dec 0.1
Key $MODKEY-KP_Add
    transset-df -a --min 0.1 --inc 0.1
#Mount/Unmount all drives
Key $MODKEY-Insert
    devmon --mount-all &
Key $MODKEY-Delete
    sync &
    devmon --unmount-removable &

KeyGroup Pulseaudio switching devices
Key $MODKEY-Shift-KP_Down
    ln -fs ~/.asoundrc_pulse ~/.asoundrc
    ps -C pulseaudio > /dev/null 2>&1 || pulseaudio --start
    if [ ! "`ps -C pulseaudio | grep defunct`" == "" ]; then
        pulseaudio --start
    fi
    pacmd set-default-sink alsa_output.pci-0000_00_14.2.analog-stereo
    for word in $(cat /tmp/inds.mypo); do
        pacmd move-sink-input $word alsa_output.pci-0000_00_14.2.analog-stereo
    done
Key $MODKEY-Shift-KP_End
    ln -fs ~/.asoundrc_pulse ~/.asoundrc
    ps -C pulseaudio > /dev/null 2>&1 || pulseaudio --start
    if [ ! "`ps -C pulseaudio | grep defunct`" == "" ]; then
        pulseaudio --start
    fi
    pacmd set-default-sink alsa_output.usb-05e1_USB_VoIP_Device-00-Device.analog-stereo
    for word in $(cat /tmp/inds.mypo); do
        pacmd move-sink-input $word alsa_output.usb-05e1_USB_VoIP_Device-00-Device.analog-stereo
    done
Key $MODKEY-Shift-KP_Left
    ln -fs ~/.asoundrc_alsa_usb ~/.asoundrc
    pulseaudio -k
Key $MODKEY-Shift-KP_Begin
    ln -fs ~/.asoundrc_alsa ~/.asoundrc
    pulseaudio -k

KeyGroup Pulseaudio per-application volume control
Key $MODKEY-KP_End
    if [ -f /tmp/inds.mypo ]; then
        pactl set-sink-input-volume $(awk '{print $1}' /tmp/inds.mypo) -- -5000
        ~/.wmii-hg/mypo 0 $(awk '{print $1}' /tmp/inds.mypo)
    fi
Key $MODKEY-KP_Down
    if [ -f /tmp/inds.mypo ]; then
        pactl set-sink-input-volume $(awk '{print $1}' /tmp/inds.mypo) -- 65536
        ~/.wmii-hg/mypo 0 $(awk '{print $1}' /tmp/inds.mypo)
    fi
Key $MODKEY-KP_Next
    if [ -f /tmp/inds.mypo ]; then
        pactl set-sink-input-volume $(awk '{print $1}' /tmp/inds.mypo) -- +5000
        ~/.wmii-hg/mypo 0 $(awk '{print $1}' /tmp/inds.mypo)
    fi

Key $MODKEY-KP_Left
    if [ -f /tmp/inds.mypo ]; then
        pactl set-sink-input-volume $(awk '{print $2}' /tmp/inds.mypo) -- -5000
        ~/.wmii-hg/mypo 1 $(awk '{print $2}' /tmp/inds.mypo)
    fi
Key $MODKEY-KP_Begin
    if [ -f /tmp/inds.mypo ]; then
        pactl set-sink-input-volume $(awk '{print $2}' /tmp/inds.mypo) -- 65536
        ~/.wmii-hg/mypo 1 $(awk '{print $2}' /tmp/inds.mypo)
    fi
Key $MODKEY-KP_Right
    if [ -f /tmp/inds.mypo ]; then
        pactl set-sink-input-volume $(awk '{print $2}' /tmp/inds.mypo) -- +5000
        ~/.wmii-hg/mypo 1 $(awk '{print $2}' /tmp/inds.mypo)
    fi

Key $MODKEY-KP_Home
    if [ -f /tmp/inds.mypo ]; then
        pactl set-sink-input-volume $(awk '{print $3}' /tmp/inds.mypo) -- -5000
        ~/.wmii-hg/mypo 2 $(awk '{print $3}' /tmp/inds.mypo)
    fi
Key $MODKEY-KP_Up
    if [ -f /tmp/inds.mypo ]; then
        pactl set-sink-input-volume $(awk '{print $3}' /tmp/inds.mypo) -- 65536
        ~/.wmii-hg/mypo 2 $(awk '{print $3}' /tmp/inds.mypo)
    fi
Key $MODKEY-KP_Prior
    if [ -f /tmp/inds.mypo ]; then
        pactl set-sink-input-volume $(awk '{print $3}' /tmp/inds.mypo) -- +5000
        ~/.wmii-hg/mypo 2 $(awk '{print $3}' /tmp/inds.mypo)
    fi

KeyGroup Tag actions
Key $MODKEY-t       # Change to another tag
	wmiir xwrite /ctl view $(wi_tags | wimenu -h "${hist}.tags" -n 50) &
Key $MODKEY-Shift-t # Retag the selected client
	# Assumes left-to-right order of evaluation
	wmiir xwrite /client/$(wi_selclient)/ctl tags $(wi_tags | wimenu -h "${hist}.tags" -n 50) &
Key $MODKEY-n	    # Move to the next tag
	wmiir xwrite /ctl view $(wi_tags | wi_nexttag)
Key $MODKEY-b	    # Move to the previous tag
	wmiir xwrite /ctl view $(wi_tags | sort -r | wi_nexttag)
!
	for i in 0 1 2 3 4 5 6 7 8 9; do
		wi_events <<!
Key $MODKEY-$i		 # Move to the numbered view
	wmiir xwrite /ctl view "$i"
Key $MODKEY-Shift-$i     # Retag selected client with the numbered tag
	wmiir xwrite /client/sel/ctl tags "$i"
!
done
wi_events -e

# WM Configuration
wmiir write /ctl <<!
	font $WMII_FONT
	focuscolors $WMII_FOCUSCOLORS
	normcolors $WMII_NORMCOLORS
	grabmod $MODKEY
	border 1
!

# WMII main action
action pywmii &

# Setup Tag Bar
IFS="$wi_newline"
wmiir rm $(wmiir ls -p /lbar) >/dev/null
seltag=$(wmiir read /tag/sel/ctl | sed 1q)
unset IFS
wi_tags | while read tag
do
    if [ "$tag" = "$seltag" ]; then
		echo colors "$WMII_TAGFOCUSCOLORS"
		echo label $tag
	else
		echo colors "$WMII_NORMCOLORS"
		echo label $tag
	fi | wmiir create "/lbar/$tag"
done

wi_eventloop
