#!/bin/sh -f
# Configure wmii
wmiiscript=wmiirc # For wmii.sh
. wmii.sh
# Settings
python ~/.wmii-hg/settings.py > /tmp/settings.wmii
var(){
    awk -F '|' "/$1/ {print \$2}" /tmp/settings.wmii
}

# Configuration Variables
MODKEY=`var modkey`
UP=`var up`
DOWN=`var down`
LEFT=`var left`
RIGHT=`var right`

# Bars
noticetimeout=5
noticebar=/rbar/!notice

# Colors tuples: "<text> <background> <border>"
export WMII_FONT=`var font`
export WMII_TERM=`var term`

export WMII_NORMCOLORS=`var normColors`
export WMII_FOCUSCOLORS=`var goodColors`
export WMII_TAGFOCUSCOLORS=`var tagFocusColors`

set -- $(echo $WMII_NORMCOLORS $WMII_FOCUSCOLORS)
echo colors $WMII_NORMCOLORS | wmiir create $noticebar

# Event processing
wi_events <<'!'
# Events
Event CreateTag
	echo colors "$WMII_NORMCOLORS$wi_newline" label "$@" | wmiir create "/lbar/$@"
Event DestroyTag
	wmiir remove "/lbar/$@"
Event FocusTag
	wmiir xwrite "/lbar/$@" colors "$WMII_TAGFOCUSCOLORS"
Event UnfocusTag
	wmiir xwrite "/lbar/$@" colors "$WMII_NORMCOLORS"
Event UrgentTag
	shift
	wmiir xwrite "/lbar/$@" label "*$@"
Event NotUrgentTag
	shift
	wmiir xwrite "/lbar/$@" label "$@"
Event LeftBarClick LeftBarDND
	shift
	wmiir xwrite /ctl view "$@"
Event Unresponsive
	{
		client=$1; shift
		msg="The following client is not responding. What would you like to do?$wi_newline"
		resp=$(wihack -transient $client \
			      xmessage -nearmouse -buttons Kill,Wait -print \
			      -fn "${WMII_FONT%%,*}" "$msg $(wmiir read /client/sel/label)")
		if [ "$resp" = Kill ]; then
			wmiir xwrite /client/$client/ctl slay &
		fi
	}&
Event Notice
	wmiir xwrite $noticebar $wi_arg
	kill $xpid 2>/dev/null # Let's hope this isn't reused...
	{ sleep $noticetimeout; wmiir xwrite $noticebar ' '; }&
	xpid = $!

# Menus
Menu Client-3-Close
	wmiir xwrite /client/$1/ctl kill
Menu Client-3-Kill
	wmiir xwrite /client/$1/ctl slay
Event ClientMouseDown
	wi_fnmenu Client $2 $1 &

Menu LBar-3-Delete
	tag=$1; clients=$(wmiir read "/tag/$tag/index" | awk '/[^#]/{print $2}')
	for c in $clients; do
		if [ "$tag" = "$(wmiir read /client/$c/tags)" ]
		then wmiir xwrite /client/$c/ctl kill
		else wmiir xwrite /client/$c/ctl tags -$tag
		fi
		[ "$tag" = "$(wi_seltag)" ] &&
			wmiir xwrite /ctl view $(wi_tags | wi_nexttag)
	done
Event LeftBarMouseDown
	wi_fnmenu LBar "$@" &

# Actions
Action showkeys
	echo "$KeysHelp" | xmessage -file - -fn ${WMII_FONT%%,*}
Action quit
	wmiir xwrite /ctl quit
Action exec
	wmiir xwrite /ctl exec "$@"
Action pywmii
    ~/.wmii-hg/wmii.py

# Key Bindings
KeyGroup Moving around
Key $MODKEY-$LEFT   # Select the client to the left
	wmiir xwrite /tag/sel/ctl select left
Key $MODKEY-$RIGHT  # Select the client to the right
	wmiir xwrite /tag/sel/ctl select right
Key $MODKEY-$UP     # Select the client above
	wmiir xwrite /tag/sel/ctl select up
Key $MODKEY-$DOWN   # Select the client below
	wmiir xwrite /tag/sel/ctl select down

KeyGroup Moving clients around
Key $MODKEY-Shift-$LEFT   # Move selected client to the left
	wmiir xwrite /tag/sel/ctl send sel left
Key $MODKEY-Shift-$RIGHT  # Move selected client to the right
	wmiir xwrite /tag/sel/ctl send sel right
Key $MODKEY-Shift-$UP     # Move selected client up
	wmiir xwrite /tag/sel/ctl send sel up
Key $MODKEY-Shift-$DOWN   # Move selected client down
	wmiir xwrite /tag/sel/ctl send sel down

KeyGroup Resizing clients
Key $MODKEY-Control-$LEFT
    wmiir xwrite /tag/sel/ctl grow sel sel right -2
Key $MODKEY-Control-$RIGHT
    wmiir xwrite /tag/sel/ctl grow sel sel right 2
Key $MODKEY-Control-$UP
    wmiir xwrite /tag/sel/ctl grow sel sel down -2
Key $MODKEY-Control-$DOWN
    wmiir xwrite /tag/sel/ctl grow sel sel down 2

KeyGroup Floating switching
Key $MODKEY-space   # Toggle between floating and managed layers
	wmiir xwrite /tag/sel/ctl select toggle
Key $MODKEY-Shift-space   # Toggle selected client between floating and managed layers
	wmiir xwrite /tag/sel/ctl send sel toggle

KeyGroup Client actions
Key $MODKEY-f # Toggle selected client's fullsceen state
	wmiir xwrite /client/sel/ctl Fullscreen toggle
Key $MODKEY-bracketright # Toggle urgent
    wmiir xwrite /client/sel/ctl urgent toggle
Key $MODKEY-q # Close client
    sc=$(wmiir read /client/sel/label)
    if [ "$sc" != "tilda" ]; then
        wmiir xwrite /client/sel/ctl kill
    fi
Key $MODKEY-Shift-q #Kill client
    sc=$(wmiir read /client/sel/label)
    if [ "$sc" != "tilda" ]; then
        wmiir xwrite /client/sel/ctl slay
    fi

KeyGroup Changing column modes
Key $MODKEY-d # Set column to default mode
	wmiir xwrite /tag/sel/ctl colmode sel default-max
Key $MODKEY-s # Set column to stack mode
	wmiir xwrite /tag/sel/ctl colmode sel stack-max
Key $MODKEY-m # Set column to max mode
	wmiir xwrite /tag/sel/ctl colmode sel stack+max

KeyGroup Running programs
Key $MODKEY-a   # Open wmii actions menu
	action $(wi_actions | wimenu -h "${hist}.actions" -n $histnum) &
Key $MODKEY-p   # Open dmenu programs menu
    echo "`wmiir ls /tag | sed '$d'`" > /tmp/tags.dm
    x=0
    while read line; do
        x=$(( $x + 6 * $(( ${#line} - 1 )) + 11 ))
    done < /tmp/tags.dm
    w=$(( 600 - $x ))
    ~/bin/dm -i -nb black -fn '-*-terminus-medium' -nf orange -sb black -p "#" -w $w -x $x &
Key $MODKEY-Return # Launch a terminal
	eval wmiir setsid $WMII_TERM &

KeyGroup Personal software
Key $MODKEY-c
	chromium &
Key $MODKEY-e
    chromium keep.google.com &
Key $MODKEY-Shift-w
    virtualbox --startvm Windows7 &
Key $MODKEY-g
	gvim &
Key $MODKEY-r
    urxvt -e canto-curses -a 127.0.0.1 -p 7070 -v &
Key $MODKEY-w
    chromium --app-id=iiooodelglhkcpgbajoejffhijaclcdg
    
KeyGroup Volume control   
Key $MODKEY-x
    ~/bin/volume up &
Key $MODKEY-z
    ~/bin/volume down &
Key $MODKEY-Shift-z
    ~/bin/volume off &
Key $MODKEY-Shift-x
    ~/bin/volume on &

KeyGroup Keyboard layouts
Key $MODKEY-i
    sed -i 's/ca(fr),ru/us,ru/g' ~/.config/gxkb/gxkb.cfg && killall gxkb && gxkb &
Key $MODKEY-Shift-i
    sed -i 's/us,ru/ca(fr),ru/g' ~/.config/gxkb/gxkb.cfg && killall gxkb && gxkb &

KeyGroup Others
Key $MODKEY-Control-Return
    ~/.wmii-hg/lstags
#Turn off mouse/touchpad
Key $MODKEY-v
    id=`xinput --list | grep "Wheel Mouse" | awk '{print $7}' | cut -f2 -d "="`
    if [ "`xinput --list-props $id | grep "Device Enabled" | awk '{print $4}'`" == "0" ]; then
        state=1
    else
        state=0
    fi
    xinput set-int-prop $id "Device Enabled" 8 $state
    synclient TouchpadOff=$(synclient -l | grep -c 'TouchpadOff.*=.*0') &
#CINEMA MODE (turn off colors)
Key $MODKEY-o
    if [ "`wmiir read /ctl | grep focuscolors | awk {'print $3'}`" == "#000000" ]; then
        wmiir xwrite /ctl focuscolors "`var goodColors`" &
        killall -SIGUSR2 dunst &
    else
        wmiir xwrite /ctl focuscolors "#999 #000 #000" &
        killall -SIGUSR1 dunst &
    fi
#Lock session (screensaver)
Key $MODKEY-KP_Enter
    slimlock
Key $MODKEY-Shift-KP_Enter
    kill `ps aux | awk '/wmii.py/ {print $2}'`
	wmiir xwrite /ctl quit
#Remove 'New messages' notification
Key $MODKEY-apostrophe
    wmiir remove /rbar/ZNotify
#System update
Key $MODKEY-F10
    rm /tmp/yaourt.updates
    urxvt -e yaourt -Syua --noconfirm &
#Screenshot
Key Print
    dbss &
#Go to Keep tag
Key $MODKEY-F11
    if [ -z "$cv" ]; then
        cv="1"
    fi
    seltag=$(wmiir read /tag/sel/ctl | sed 1q)
    if [ $seltag == "Keep" ]; then
        wmiir xwrite /ctl view $cv
    else
        cv=$seltag
        wmiir xwrite /ctl view Keep
    fi
Key $MODKEY-Shift-F11
    wmiir xwrite /rbar/\!notice colors "`var warnColors`"
    wmiir xwrite /rbar/\!notice label "Power off..."
    baconf
    systemctl poweroff -i
Key $MODKEY-Shift-F10
    wmiir xwrite /rbar/\!notice colors "`var warnColors`"
    wmiir xwrite /rbar/\!notice label "Reboot..."
    baconf
    systemctl reboot -i
#Change wallpaper
Key $MODKEY-Print
    feh --bg-fill --randomize --recursive Dropbox/Pictures
#Increase/decrease transparency of current window
Key $MODKEY-KP_Subtract
    transset-df -a --min 0.1 --dec 0.1
Key $MODKEY-KP_Add
    transset-df -a --min 0.1 --inc 0.1
#Mount/Unmount all drives
Key $MODKEY-Insert
    devmon --ignore-device /dev/sdb --ignore-device /dev/sdc --ignore-device /dev/sdd --ignore-device /dev/sde --mount-all &
Key $MODKEY-Delete
    sync &
    devmon --unmount-removable &

KeyGroup Pulseaudio switching devices
Key $MODKEY-Shift-KP_Down
    cp ~/.asoundrc_pulse ~/.asoundrc
    ps -C pulseaudio > /dev/null 2>&1 || pulseaudio --start
    if [ ! "`ps -C pulseaudio | grep defunct`" == "" ]; then
        pulseaudio --start
    fi
    pacmd set-default-sink `pactl list | awk '/alsa_output.pci.*analog-stereo$/ {print $2; exit}'`
    for word in $(cat /tmp/inds.mypo); do
        pacmd move-sink-input $word `pactl list | awk '/alsa_output.pci.*analog-stereo$/ {print $2; exit}'`
    done
    ~/bin/mypo
Key $MODKEY-Shift-KP_End
    cp ~/.asoundrc_pulse ~/.asoundrc
    ps -C pulseaudio > /dev/null 2>&1 || pulseaudio --start
    if [ ! "`ps -C pulseaudio | grep defunct`" == "" ]; then
        pulseaudio --start
    fi
    pacmd set-default-sink alsa_output.usb-05e1_USB_VoIP_Device-00-Device.analog-stereo
    for word in $(cat /tmp/inds.mypo); do
        pacmd move-sink-input $word alsa_output.usb-05e1_USB_VoIP_Device-00-Device.analog-stereo
    done
    ~/bin/mypo
Key $MODKEY-Shift-KP_Left
    cp ~/.asoundrc_alsa ~/.asoundrc
    sed -i 's/CARDNAME/Device/g' ~/.asoundrc
    pulseaudio -k
Key $MODKEY-Shift-KP_Begin
    cp ~/.asoundrc_alsa ~/.asoundrc
    sed -i "s/CARDNAME/`awk '/\[SB|\[MID/ {print substr($2,2)}' /proc/asound/cards`/g" ~/.asoundrc
    pulseaudio -k

KeyGroup Pulseaudio per-application volume control
Key $MODKEY-KP_End
    if [ -f /tmp/inds.mypo ]; then
        pactl set-sink-input-volume `cat /tmp/cind.mypo` -5000
    fi
Key $MODKEY-KP_Down
    if [ -f /tmp/inds.mypo ]; then
        pactl set-sink-input-volume `cat /tmp/cind.mypo` 65536
    fi
Key $MODKEY-KP_Next
    if [ -f /tmp/inds.mypo ]; then
        pactl set-sink-input-volume `cat /tmp/cind.mypo` +5000
    fi
Key $MODKEY-KP_Left
    ~/bin/mypo prev
Key $MODKEY-KP_Right
    ~/bin/mypo next

Key $MODKEY-KP_Home
    amixer -q sset Capture 5000-
    notify-send "Capture" -t 500 -h int:value:`amixer | awk '/Mono: Capture/ {print $4} /Left: Capture/ {print $5}' | tr -d '[]%'` -h string:fgcolor:#faaa00 -h string:bgcolor:#000000
Key $MODKEY-KP_Up
    amixer -q sset Capture 65536
    notify-send "Capture" -t 500 -h int:value:`amixer | awk '/Mono: Capture/ {print $4} /Left: Capture/ {print $5}' | tr -d '[]%'` -h string:fgcolor:#faaa00 -h string:bgcolor:#000000
Key $MODKEY-KP_Prior
    amixer -q sset Capture 5000+
    notify-send "Capture" -t 500 -h int:value:`amixer | awk '/Mono: Capture/ {print $4} /Left: Capture/ {print $5}' | tr -d '[]%'` -h string:fgcolor:#faaa00 -h string:bgcolor:#000000

KeyGroup Tag actions
Key $MODKEY-t       # Change to another tag
	wmiir xwrite /ctl view $(wi_tags | wimenu -h "${hist}.tags" -n 50) &
Key $MODKEY-Shift-t # Retag the selected client
	# Assumes left-to-right order of evaluation
	wmiir xwrite /client/$(wi_selclient)/ctl tags $(wi_tags | wimenu -h "${hist}.tags" -n 50) &
Key $MODKEY-n	    # Move to the next tag
	wmiir xwrite /ctl view $(wi_tags | wi_nexttag)
Key $MODKEY-b	    # Move to the previous tag
	wmiir xwrite /ctl view $(wi_tags | sort -r | wi_nexttag)
!
	for i in 0 1 2 3 4 5 6 7 8 9; do
		wi_events <<!
Key $MODKEY-$i		 # Move to the numbered view
	wmiir xwrite /ctl view "$i"
Key $MODKEY-Shift-$i     # Retag selected client with the numbered tag
	wmiir xwrite /client/sel/ctl tags "$i"
#LSTAGS
Key $MODKEY-Control-$i
    ~/.wmii-hg/lstags $i
!
done
wi_events -e

# WM Configuration
wmiir write /ctl <<!
	font $WMII_FONT
	focuscolors $WMII_FOCUSCOLORS
	normcolors $WMII_NORMCOLORS
	grabmod $MODKEY
	border 1
!

# WMII main action
action pywmii &

# Setup Tag Bar
IFS="$wi_newline"
wmiir rm $(wmiir ls -p /lbar) >/dev/null
seltag=$(wmiir read /tag/sel/ctl | sed 1q)
unset IFS
wi_tags | while read tag
do
    if [ "$tag" = "$seltag" ]; then
		echo colors "$WMII_TAGFOCUSCOLORS"
		echo label $tag
	else
		echo colors "$WMII_NORMCOLORS"
		echo label $tag
	fi | wmiir create "/lbar/$tag"
done

wi_eventloop
