#!/bin/sh -f
# Configure wmii
wmiiscript=wmiirc # For wmii.sh
. wmii.sh

# Configuration Variables
MODKEY=Mod4
UP=k
DOWN=j
LEFT=h
RIGHT=l

# Bars
noticetimeout=5
noticebar=/rbar/!notice

# Colors tuples: "<text> <background> <border>"
export WMII_NORMCOLORS='#000 #999 #000'
export WMII_FOCUSCOLORS='#000 #fc5 #000'

export GOODCOLORS='#000 #6c6 #000'
export MIDCOLORS='#000 #7c8 #000'
export BADCOLORS='#000 #c66 #000'
export SOUNDCOLORS='#000 #6cc #000'

export WMII_BACKGROUND='#000000'
export WMII_FONT='-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'

set -- $(echo $WMII_NORMCOLORS $WMII_FOCUSCOLORS)
export WMII_TERM="urxvt"

# Menu history
hist="${WMII_CONFPATH%%:*}/history"
histnum=5000

# Column Rules
wmiir write /colrules <<!
    /0/ -> 20+80 # For skype mini-window on the left side
    /2/ -> 50+50 # For two Thunars / 2 opera windows
    /.*/ -> 62+38 # Golden Ratio
!

# Tagging Rules
wmiir write /rules <<!
/Canto/ force-tags=RSS
/Skype/ force-tags=0
/Steam/ force-tags=steam
!

# Status Bar Info

status82(){
    echo -n label $(amixer | grep "Left: Playback" | awk {'print $5'} | cut -d "[" -f2 | cut -d "%" -f1)
}

status10(){
    echo -n label $(free -mh | grep /cache | awk '{print $4}') 'M'
}

status20(){
    echo -n label $(df -h / | grep / | awk '{print $5}' | sed 's/%//') '/'
}

status30(){
    echo -n label $(df -h /home | grep home | awk '{print $5}' | sed 's/%//') 'H'
}

status40(){
    echo -n label $(df -h /mnt/cloud | grep cloud | awk '{print $5}' | sed 's/%//') 'C'
}

status50(){
    echo -n label $(df -h /mnt/backup | grep backup | awk '{print $5}' | sed 's/%//') 'B'
}

status60(){
    echo -n label $(sensors | grep -m 1 temp1 | awk '{print $2}' | cut -c 2-3)
}

status70(){
    echo -n label $(cat /proc/cpuinfo | grep -m 1 MHz | awk '{printf "%.0f\n", $4}')
}

status80(){
    echo -n label $(nvidia-settings -q=GPUCoreTemp | grep -m 1 ewanhost | awk '{print $4}' | cut -c1-2)
}

status90(){
    echo -n label $(uptime | sed 's/.*://; s/, / /g')
}

status910(){
    echo -n label $(date +%a\ %b\ %d\ %T)
}

# Generic overridable startup details
startup() {
    ~/runonce.sh &

    pactl set-sink-port alsa_output.pci-0000_00_14.2.analog-stereo analog-output-headphones

    chromium --no-startup-window &
    copy &

    deluge &
#    screen -dmS irssi irssi &
    #screen -dmS rtorrent rtorrent &

    dropboxd &
    feh --bg-scale --randomize ~/Dropbox/Pictures &
    ~/.dotfiles/scripts/pic ~/Dropbox/Pictures 300 &
    tilda &
    gxkb &
    kalu &
    urxvt -name Canto -e canto-curses &

    #skype &
    #steam &
}

wi_runconf -s wmiirc_local
startup
echo colors $WMII_NORMCOLORS | wmiir create $noticebar

# Event processing
wi_events <<'!'
# Events
Event CreateTag
	echo colors "$WMII_NORMCOLORS$wi_newline" label "$@" | wmiir create "/lbar/$@"
Event DestroyTag
	wmiir remove "/lbar/$@"
Event FocusTag
	wmiir xwrite "/lbar/$@" colors "$WMII_FOCUSCOLORS"
Event UnfocusTag
	wmiir xwrite "/lbar/$@" colors "$WMII_NORMCOLORS"
Event UrgentTag
	shift
	wmiir xwrite "/lbar/$@" label "*$@"
Event NotUrgentTag
	shift
	wmiir xwrite "/lbar/$@" label "$@"
Event LeftBarClick LeftBarDND
	shift
	wmiir xwrite /ctl view "$@"
Event Unresponsive
	{
		client=$1; shift
		msg="The following client is not responding. What would you like to do?$wi_newline"
		resp=$(wihack -transient $client \
			      xmessage -nearmouse -buttons Kill,Wait -print \
			      -fn "${WMII_FONT%%,*}" "$msg $(wmiir read /client/sel/label)")
		if [ "$resp" = Kill ]; then
			wmiir xwrite /client/$client/ctl slay &
		fi
	}&
Event Notice
	wmiir xwrite $noticebar $wi_arg

	kill $xpid 2>/dev/null # Let's hope this isn't reused...
	{ sleep $noticetimeout; wmiir xwrite $noticebar ' '; }&
	xpid = $!

# Menus
Menu Client-3-Close
	wmiir xwrite /client/$1/ctl kill
Menu Client-3-Kill
	wmiir xwrite /client/$1/ctl slay
Event ClientMouseDown
	wi_fnmenu Client $2 $1 &

Menu LBar-3-Delete
	tag=$1; clients=$(wmiir read "/tag/$tag/index" | awk '/[^#]/{print $2}')
	for c in $clients; do
		if [ "$tag" = "$(wmiir read /client/$c/tags)" ]
		then wmiir xwrite /client/$c/ctl kill
		else wmiir xwrite /client/$c/ctl tags -$tag
		fi
		[ "$tag" = "$(wi_seltag)" ] &&
			wmiir xwrite /ctl view $(wi_tags | wi_nexttag)
	done
Event LeftBarMouseDown
	wi_fnmenu LBar "$@" &

# Actions
Action showkeys
	echo "$KeysHelp" | xmessage -file - -fn ${WMII_FONT%%,*}
Action quit
	wmiir xwrite /ctl quit
Action exec
	wmiir xwrite /ctl exec "$@"
Action rehash
	wi_proglist $PATH >$progsfile
Action rssitems
    while true; do
        if [ -f /tmp/rssitems ]; then
            wmiir xwrite /lbar/RSS colors "$GOODCOLORS"
            rm /tmp/rssitems
        fi
        sleep 5
    done
Action timedate
	echo colors "$WMII_FOCUSCOLORS" | wmiir create /rbar/status910
    while true; do
        status910 | wmiir write /rbar/status910
        sleep 1
    done
Action pystatus
    ~/.wmii-hg/status.py
Action status
	set +xv
    echo colors "$SOUNDCOLORS" | wmiir create /rbar/status82
	echo colors "$GOODCOLORS" | wmiir create /rbar/status10
	echo colors "$GOODCOLORS" | wmiir create /rbar/status20
	echo colors "$GOODCOLORS" | wmiir create /rbar/status30
	echo colors "$GOODCOLORS" | wmiir create /rbar/status40
	echo colors "$GOODCOLORS" | wmiir create /rbar/status50
	echo colors "$GOODCOLORS" | wmiir create /rbar/status60
	echo colors "$GOODCOLORS" | wmiir create /rbar/status70
	echo colors "$GOODCOLORS" | wmiir create /rbar/status80
	echo colors "$WMII_FOCUSCOLORS" | wmiir create /rbar/status90
    while true; do
        check10=$(free -m | grep /cache | awk '{print $4}')
        check20=$(df -h / | grep / | awk '{print $5}' | sed 's/%//')
        check30=$(df -h /home | grep home | awk '{print $5}' | sed 's/%//')
        check40=$(df -h /mnt/cloud | grep cloud | awk '{print $5}' | sed 's/%//')
        check50=$(df -h /mnt/backup | grep backup | awk '{print $5}' | sed 's/%//')
        check60=$(sensors | grep -m 1 temp1 | awk '{print $2}' | cut -c 2-3)
        check80=$(nvidia-settings -q=GPUCoreTemp | grep -m 1 ewanhost | awk '{print $4}' | cut -c1-2)
#        check90=$(uptime | sed 's/.*://; s/, / /g' | awk '{print $2}' | cut -c1-1)

        if [ $check10 -gt 3000 ]; then
            nc10="$GOODCOLORS"
        elif [ $check10 -gt 1000 ]; then
            nc10="$MIDCOLORS"
        else
            nc10="$BADCOLORS"
        fi

        if [ $check20 -lt 45 ]; then
            nc20="$GOODCOLORS"
        elif [ $check20 -lt 75 ]; then
            nc20="$MIDCOLORS"
        else
            nc20="$BADCOLORS"
        fi

        if [ $check30 -lt 45 ]; then
            nc30="$GOODCOLORS"
        elif [ $check30 -lt 75 ]; then
            nc30="$MIDCOLORS"
        else
            nc30="$BADCOLORS"
        fi

        if [ $check40 -lt 45 ]; then
            nc40="$GOODCOLORS"
        elif [ $check40 -lt 75 ]; then
            nc40="$MIDCOLORS"
        else
            nc40="$BADCOLORS"
        fi

        if [ $check50 -lt 45 ]; then
            nc50="$GOODCOLORS"
        elif [ $check50 -lt 75 ]; then
            nc50="$MIDCOLORS"
        else
            nc50="$BADCOLORS"
        fi

        if [ $check60 -lt 40 ]; then
            nc60="$GOODCOLORS"
        elif [ $check60 -lt 50 ]; then
            nc60="$MIDCOLORS"
        else
            nc60="$BADCOLORS"
        fi

        if [ $check80 -lt 40 ]; then
            nc80="$GOODCOLORS"
        elif [ $check80 -lt 52 ]; then
            nc80="$MIDCOLORS"
        else
            nc80="$BADCOLORS"
        fi

        python ~/.wmii-hg/test.py

        wmiir xwrite /rbar/status10 colors "$nc10"
        wmiir xwrite /rbar/status20 colors "$nc20"
        wmiir xwrite /rbar/status30 colors "$nc30"
        wmiir xwrite /rbar/status40 colors "$nc40"
        wmiir xwrite /rbar/status50 colors "$nc50"
        wmiir xwrite /rbar/status60 colors "$nc60"
        wmiir xwrite /rbar/status80 colors "$nc80"
        wmiir xwrite /rbar/status90 colors "$NC90"
        status82 | wmiir write /rbar/status82
        status10 | wmiir write /rbar/status10
        status20 | wmiir write /rbar/status20
        status30 | wmiir write /rbar/status30
        status40 | wmiir write /rbar/status40
        status50 | wmiir write /rbar/status50
        status60 | wmiir write /rbar/status60
        status70 | wmiir write /rbar/status70
        status80 | wmiir write /rbar/status80
        status90 | wmiir write /rbar/status90

        sleep 1
    done

# Key Bindings
KeyGroup Moving around
Key $MODKEY-$LEFT   # Select the client to the left
	wmiir xwrite /tag/sel/ctl select left
Key $MODKEY-$RIGHT  # Select the client to the right
	wmiir xwrite /tag/sel/ctl select right
Key $MODKEY-$UP     # Select the client above
	wmiir xwrite /tag/sel/ctl select up
Key $MODKEY-$DOWN   # Select the client below
	wmiir xwrite /tag/sel/ctl select down

Key $MODKEY-space   # Toggle between floating and managed layers
	wmiir xwrite /tag/sel/ctl select toggle

KeyGroup Moving through stacks
Key $MODKEY-Control-$UP    # Select the stack above
	wmiir xwrite /tag/sel/ctl select up stack
Key $MODKEY-Control-$DOWN  # Select the stack below
	wmiir xwrite /tag/sel/ctl select down stack

KeyGroup Moving clients around
Key $MODKEY-Shift-$LEFT   # Move selected client to the left
	wmiir xwrite /tag/sel/ctl send sel left
Key $MODKEY-Shift-$RIGHT  # Move selected client to the right
	wmiir xwrite /tag/sel/ctl send sel right
Key $MODKEY-Shift-$UP     # Move selected client up
	wmiir xwrite /tag/sel/ctl send sel up
Key $MODKEY-Shift-$DOWN   # Move selected client down
	wmiir xwrite /tag/sel/ctl send sel down

Key $MODKEY-Shift-space   # Toggle selected client between floating and managed layers
	wmiir xwrite /tag/sel/ctl send sel toggle

KeyGroup Client actions
Key $MODKEY-f # Toggle selected client's fullsceen state
	wmiir xwrite /client/sel/ctl Fullscreen toggle
Key Control-q # Close client
    sc=$(wmiir read /client/sel/label)
    if [ "$sc" != "tilda" ] && [ "$sc" != "canto-curses" ]; then
        wmiir xwrite /client/sel/ctl kill
    fi

#My keys configuration
Key $MODKEY-c
	chromium &
Key $MODKEY-g
	gvim &
Key $MODKEY-p
    xboomx &
Key $MODKEY-q
    #urxvt -e screen -r rtorrent
    deluge &
Key $MODKEY-w
    urxvt -e alsamixer &
Key $MODKEY-x
	amixer -q sset Master 2500+ &
    wmiir xwrite /rbar/Status_a8 label $(amixer | grep "Left: Playback" | awk {'print $5'} | cut -d "[" -f2 | cut -d "%" -f1)
Key $MODKEY-z
	amixer -q sset Master 2500- &
    wmiir xwrite /rbar/Status_a8 label $(amixer | grep "Left: Playback" | awk {'print $5'} | cut -d "[" -f2 | cut -d "%" -f1)

Key $MODKEY-i
    sed -i 's/ca(fr),ru/us,ru/g' ~/.config/gxkb.cfg && killall gxkb && gxkb &
Key $MODKEY-Shift-i
    sed -i 's/us,ru/ca(fr),ru/g' ~/.config/gxkb.cfg && killall gxkb && gxkb &

Key $MODKEY-Shift-x
    xcompmgr &
Key $MODKEY-Shift-z
    killall xcompmgr &

Key XF86Sleep
    dbss &
Key XF86WakeUp
    urxvt -e sudo yaourt -Syua --noconfirm &
Key XF86PowerOff
    if [ $cv == "" ]; then
        cv="1"
    fi
    seltag=$(wmiir read /tag/sel/ctl | sed 1q)
    if [ $seltag == "RSS" ]; then
        wmiir xwrite /ctl view $cv
    else
        cv=$seltag
        wmiir xwrite /ctl view RSS
    fi

KeyGroup Changing column modes
Key $MODKEY-d # Set column to default mode
	wmiir xwrite /tag/sel/ctl colmode sel default-max
Key $MODKEY-s # Set column to stack mode
	wmiir xwrite /tag/sel/ctl colmode sel stack-max
Key $MODKEY-m # Set column to max mode
	wmiir xwrite /tag/sel/ctl colmode sel stack+max

KeyGroup Running programs
Key $MODKEY-a      # Open wmii actions menu
	action $(wi_actions | wimenu -h "${hist}.actions" -n $histnum) &

Key $MODKEY-Return # Launch a terminal
	eval wmiir setsid $WMII_TERM &

KeyGroup Other
Key $MODKEY-Control-t # Toggle all other key bindings
	case $(wmiir read /keys | wc -l | tr -d ' \t\n') in
	0|1)
		echo -n "$Keys" | wmiir write /keys
		wmiir xwrite /ctl grabmod $MODKEY;;
	*)
		wmiir xwrite /keys $MODKEY-Control-t
		wmiir xwrite /ctl grabmod Mod3;;
	esac

KeyGroup Tag actions
Key $MODKEY-t       # Change to another tag
	wmiir xwrite /ctl view $(wi_tags | wimenu -h "${hist}.tags" -n 50) &
Key $MODKEY-Shift-t # Retag the selected client
	# Assumes left-to-right order of evaluation
	wmiir xwrite /client/$(wi_selclient)/ctl tags $(wi_tags | wimenu -h "${hist}.tags" -n 50) &
Key $MODKEY-n	    # Move to the next tag
	wmiir xwrite /ctl view $(wi_tags | wi_nexttag)
Key $MODKEY-b	    # Move to the previous tag
	wmiir xwrite /ctl view $(wi_tags | sort -r | wi_nexttag)
!
	for i in 0 1 2 3 4 5 6 7 8 9; do
		wi_events <<!
Key $MODKEY-$i		 # Move to the numbered view
	wmiir xwrite /ctl view "$i"
Key $MODKEY-Shift-$i     # Retag selected client with the numbered tag
	wmiir xwrite /client/sel/ctl tags "$i"
!
done
wi_events -e

# WM Configuration
wmiir write /ctl <<!
	font $WMII_FONT
	focuscolors $WMII_FOCUSCOLORS
	normcolors $WMII_NORMCOLORS
	grabmod $MODKEY
	border 1
!
xsetroot -solid "$WMII_BACKGROUND" &

# Misc
progsfile="$(wmiir namespace)/.proglist"
#action status &
action pystatus &
action timedate &
action rssitems &
wi_proglist $PATH >$progsfile &

# Setup Tag Bar
IFS="$wi_newline"
wmiir rm $(wmiir ls -p /lbar) >/dev/null
seltag=$(wmiir read /tag/sel/ctl | sed 1q)
unset IFS
wi_tags | while read tag
do
#    if [ "$tag" != "rss" ]; then
    if [ "$tag" = "$seltag" ]; then
		echo colors "$WMII_FOCUSCOLORS"
		echo label $tag
	else
		echo colors "$WMII_NORMCOLORS"
		echo label $tag
	fi | wmiir create "/lbar/$tag"
#    fi
done

witray &

wi_eventloop
