# Enable 256 colors
set -g default-terminal "screen-256color"

# Set C-a to be default shortcut
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Shorten command delay
set -sg escape-time 1

# Vim-like splitting
bind s split-window -h
bind v split-window -v

# Vim-like motion
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Cycle using C-h and C-l
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Vim-like resize
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# Colors
set-option -g pane-border-fg colour235
set-option -g pane-active-border-fg colour240
set-option -g message-bg black
set-option -g message-fg brightred

set-option -g status on
set -g status-interval 5
set -g status-justify centre

setw -g monitor-activity on
set -g visual-activity on

set -g status-bg colour235
set -g status-fg yellow
set-option -g status-attr dim

set-window-option -g window-status-fg brightblue #base0
set-window-option -g window-status-bg colour236 
set-window-option -g window-status-attr dim

set-window-option -g window-status-current-fg brightred #orange
set-window-option -g window-status-current-bg colour236 
set-window-option -g window-status-current-attr bright
