set shell=/bin/bash "Set external shell
set nocompatible    "Be iMproved
filetype off        "Required by Vundle

"Execute VUNDLE
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

"---------- Vundle Bundles ----------
Bundle 'gmarik/vundle'
"Coloring #abc and #aabbcc
Bundle 'lilydjwg/colorizer'
"Git wrapper
Bundle 'tpope/vim-fugitive'
"Diff cool thing
Bundle "airblade/vim-gitgutter"
"Snipmate depencencies
Bundle 'MarcWeber/vim-addon-mw-utils'
Bundle 'tomtom/tlib_vim'
"Snipmate itself
Bundle 'garbas/vim-snipmate'
"Snippets itself :)
Bundle 'honza/vim-snippets'
"Autoclosing brackets
Bundle 'Raimondi/delimitMate'
"Python autocompletion (jedi)
Bundle 'davidhalter/jedi-vim'
"Instead of powerline - airline (viml instead of python+corrupted fonts)
Bundle "bling/vim-airline"
"I need this for habrahabr's article
Bundle "Lokaltog/vim-easymotion"
"For RST+Sphinx
"Bundle "Rykka/riv.vim"
"Matcher for ctrlp
Bundle "FelikZ/ctrlp-py-matcher"
"Find file (like command-t)
Bundle "kien/ctrlp.vim"
"Visualize undo/redo tree
Bundle "vim-scripts/Gundo"
"For %-matching if/then/else and <tags>
Bundle "tmhedberg/matchit"
"For quickly changing tags
Bundle "tpope/vim-surround"
"For filesystem browsing
Bundle "scrooloose/nerdtree"
"Syntax checking
Bundle "scrooloose/syntastic"
"Commenting multiple lines
Bundle "scrooloose/nerdcommenter"
"Finish Vundle, set filetype
filetype plugin indent on

"---------- General ----------
set history=5000
"Autoread when file is changed from the outside
set autoread
"Setup backup&swap dirs
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
"Set hidden buffer
set hidden
"STRANGE option (but good perfomance)
""set lazyredraw (dont redraw while executing macros)
"Searching
set ignorecase
set smartcase
set hlsearch
set incsearch
"Encoding
set encoding=utf8
"Backspace acts like normal (Do I need it?)
"Set backspace=eol,start,indent
"For autocd
set autochdir

"---------- Colors/interface ----------
colorscheme desert
syntax on
"Set scrolloff to 5 lines
set so=5
"Turn on wildmenu (highlight commandline Tab)
set wildmenu
set wildignore=*.o,*~
"Show matching brackets / blink time
set showmatch
set mat=2
"Remove all gui menus (only hardcore)
set guioptions=ac
"Little bit margin to the left
set foldcolumn=1
"TABS configuration
set expandtab		"Turn Tab to Spaces
set smarttab		"Backspace delete all Spaces
set shiftwidth=4	"1 Tab = 4 Spaces
set tabstop=4		"Real Tab length = 4 Spaces
set autoindent
set smartindent
"TABS for html
autocmd FileType html :setlocal sw=2 ts=2 sts=2
"NoSmartIndent for python
autocmd FileType python :setlocal nosmartindent
"Tabs for RST
autocmd FileType rst :setlocal shiftwidth=3
autocmd FileType rst :setlocal tabstop=3
set number
"Highlight OVER 80
""highlight OverLength ctermbg=red ctermfg=white guibg=#592929
""match OverLength /\%81v.\+/
"Autocompletion pink color remove
:highlight Pmenu guibg=black guifg=yellow
:highlight PmenuSel guibg=green

"---------- Mapping ----------
"Timeout ,g vs ,gv (default=1000)
set timeoutlen=500
"Leader key
let mapleader=","
let g:mapleader=","
"Easy edit .vimrc
nmap <silent> ,ev :e $MYVIMRC<cr>
nmap <silent> ,sv :so $MYVIMRC<cr>
"Fast saving / sudo saving
nmap <leader>w :w!<cr>
"Now I'm using this for buffer closing
"nmap <leader>q :q<cr>
cmap w!! w !sudo tee > /dev/null %
"Easy windows switching
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
"Close current buffer
map <leader>bd :bd<cr>
"Close all the buffers
map <leader>ba :1,1000 bd!<cr>
"Managing tabs
"map <leader>tn :tabnew<cr>
"map <leader>to :tabonly<cr>
"map <leader>tq :tabclose<cr>
"Just for wrapping text browsing
map j gj
map k gk
"Don't jump on *
nnoremap * *N
"Turn off lights
nnoremap <F8> :nohlsearch<CR>
"Whitespaces signs
if has('multi_byte')
    if version >= 700
        set listchars=tab:▸\ ,eol:¬
    else
        set listchars=tab:»\ ,trail:·,eol:¶,extends:>,precedes:<,nbsp:_
    endif
endif
nmap <leader>l :set list!<CR>
"Moving through tabs
"map <leader>n <esc>:tabprevious<CR>
"map <leader>m <esc>:tabnext<CR>
"Moving through buffers
map <C-tab> <esc>:bnext<CR>
"Close buffer without loosing split
map <leader>q :bp\|bd #<cr>
"Sort alphabetically :)
vnoremap <Leader>s :sort<CR>
"Moving code blocks
vnoremap < <gv
vnoremap > >gv
"Run python
verbose nmap <F5>!python %
"HEX MODE
map <leader>h :%!xxd<CR>
map <leader>r :%!xxd -r<CR>

"---------- Plugins ----------

"DelimitMate
let delimitMate_expand_space=1
let delimitMate_expand_cr=1

"Snipmate Tab remap
"map <C-j> <Plug>snipMateNextOrTrigger

"AutoCompletion colors
""highlight Pmenu guibg=black

"For Airline for working with 1 window
""set laststatus=2

"YCM
""let g:ycm_autoclose_preview_window_after_completion=1
""nnoremap <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>

"AirLine
let g:airline_theme = 'dark'
let g:airline_enable_fugitive=1 "Fugitive
""let g:airline_enable_syntastic=1 "Syntastic
let g:airline_left_sep = '▶'
let g:airline_right_sep = '◀'
let g:airline_linecolumn_prefix = '¶ '
let g:airline_fugitive_prefix = '⎇ '
let g:airline_paste_symbol = 'p'

""let g:airline_section_c = '%t ' "Separate sections change

""let g:airline#extensions#tagbar#enabled = 1 "Tagbar support
""let g:airline#extensions#syntastic#enabled=1


map <leader>f :CommandT<CR>
map <leader>b :CommandTBuffer<CR>


"Python-mode
"
"Just BECAUSE I NEED IT
map <C-j> <C-W>j

"Spellchecking
set spell spelllang=en,ru spellfile=$HOME/.vim/spell/my.utf-8.add

"Defining new filetypes
au BufNewFile,BufRead *.info set filetype=info
"Markdown syntax
au BufNewFile,BufRead *.md set filetype=markdown

"Strange
"set grepprg=grep\ -nH\ $*

"---------- Useful Mappings ----------
"For compiling Ino project
nnoremap <leader>ac :!(cd ..; ino build)<CR>
nnoremap <leader>au :!(cd ..; ino upload)<CR>
nnoremap <leader>as :!(cd ..; ino serial)<CR>

"---------- Plugins ----------
"vim-fugitive
nnoremap <leader>ga :Git add %:p<CR><CR>
nnoremap <leader>gb :Gblame<CR>
nnoremap <leader>gia :Git add -A<CR>
nnoremap <leader>gic :Gcommit -v<CR>
nnoremap <leader>gic! :Gcommit -v --amend<CR>
nnoremap <leader>gica :Gcommit -av<CR>
nnoremap <leader>gica! :Gcommit -av --amend<CR>
nnoremap <leader>gim :Git merge --no-ff<CR>
nnoremap <leader>gip :Git push origin --all<CR>
nnoremap <leader>gis :Gstatus<CR>
nnoremap <leader>gid :Gdiff<CR>
nnoremap <leader>gco :Git checkout<Space>
"vim-gitgutter
highlight clear SignColumn
highlight GitGutterAdd guibg=black
highlight GitGutterAdd guifg=lime
highlight GitGutterChange guibg=black
highlight GitGutterChange guifg=cyan
highlight GitGutterDelete guibg=black
highlight GitGutterDelete guifg=red
highlight GitGutterChangeDelete guibg=black
highlight GitGutterChangeDelete guifg=yellow
"Ctrlp
let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
    \ --ignore .git
    \ --ignore "**/*.pyc"
    \ -g ""'
let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
nnoremap <C-a> :CtrlP /mnt/cloud/Dropbox<CR>
"Gundo
nnoremap <F4> :GundoToggle<CR>
"NerdTree
nnoremap <F5> :NERDTree<CR>
