set shell=/bin/bash "Set external shell
set nocompatible    "Be iMproved
filetype off        "Required by Vundle

"Spellchecking
set spell spelllang=en,ru spellfile=$HOME/.vim/spell/my.utf-8.add
"Encoding
set encoding=utf8

"Execute VUNDLE
set rtp+=~/.vim/bundle/vundle
call vundle#begin()
imap <A-z> <C-^>

"---------- Vundle Bundles ----------
Plugin 'gmarik/vundle'

"RusMode
Plugin 'ruscmd'

"Coloring #abc and #aabbcc
Plugin 'lilydjwg/colorizer'

"Most recent files
Plugin 'yegappan/mru'
nmap <F9> :MRU<CR>

"Completion engine
"Plugin 'OmniSharp/omnisharp'
"Plugin 'tpope/vim-dispatch'
Plugin 'Shougo/neocomplete'
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_select = 1
autocmd FileType cs setlocal omnifunc=OmniSharp#Complete

"Git wrapper + diffs
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'

"Fast snippets engine + snippets
Plugin 'sirver/ultisnips'
Plugin 'honza/vim-snippets'
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

"Autoclosing brackets
Plugin 'jiangmiao/auto-pairs'

"Statusbar
Plugin 'bling/vim-airline'
let g:airline_theme = 'dark'
let g:airline#extensions#tabline#enabled = 1
set laststatus=2 "Work with 1 window

"Browsing through file
Plugin 'justinmk/vim-sneak'
let g:sneak#use_ic_scs = 1
nmap f <Plug>Sneak_s
nmap F <Plug>Sneak_S

"Fuzzy files find + SilverSearcher
Plugin 'FelikZ/ctrlp-py-matcher'
Plugin 'kien/ctrlp.vim'
let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
    \ --ignore .git
    \ --ignore "**/*.pyc"
    \ -g ""'
let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }

"%-matching for if/then/else, html, latex
Plugin 'tmhedberg/matchit'

"For quickly changing tags
Plugin 'tpope/vim-surround'

"Syntax checking
Plugin 'scrooloose/syntastic'

"For tags
Plugin 'majutsushi/tagbar'
nmap <F7> :TagbarToggle<CR>

"Finish Vundle, set filetype
call vundle#end()
filetype plugin indent on

"---------- General ----------
set history=5000
"Autoread when file is changed from the outside
set autoread
"Setup backup&swap dirs
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
"Allow multiple files at once
set hidden
"Don't redraw while executing macros
set lazyredraw
"Searching
set ignorecase
set smartcase
set hlsearch
set incsearch
"Autochange PWD
set autochdir
"Filetypes
au BufNewFile,BufRead *.info set filetype=info
au BufNewFile,BufRead *.md set filetype=markdown
au BufNewFile,BufRead *.tex set filetype=tex

"---------- Colors/interface ----------
colorscheme desert
syntax on
"Set scrolloff to 5 lines
set so=5
"Turn on wildmenu (highlight commandline Tab)
set wildmenu
set wildignore=*.o,*~
"Highlight matching brackets
set showmatch
"Remove all gui menus
set guioptions=ac
"TABS configuration
set expandtab		"Turn Tab to Spaces
set smarttab		"Backspace delete all Spaces
set shiftwidth=4	"1 Tab = 4 Spaces
set tabstop=4		"Real Tab length = 4 Spaces
set autoindent
set smartindent
"TABS for html
autocmd FileType html :setlocal sw=2 ts=2 sts=2
"NoSmartIndent for python
autocmd FileType python :setlocal nosmartindent
"Lines numbering
set number
"Highlight OVER 80
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
autocmd FileType c,python,css,sh match OverLength /\%81v.\+/
"Autocompletion better colors
:highlight Pmenu guibg=black guifg=#970
:highlight PmenuSel guibg=#770
"GitGutter colors
highlight clear SignColumn
highlight GitGutterAdd guibg=black
highlight GitGutterAdd guifg=lime
highlight GitGutterChange guibg=black
highlight GitGutterChange guifg=cyan
highlight GitGutterDelete guibg=black
highlight GitGutterDelete guifg=red
highlight GitGutterChangeDelete guibg=black
highlight GitGutterChangeDelete guifg=yellow

"---------- Mapping ----------
set timeoutlen=500 "Multiple keys timeout
"Leader key
let mapleader=","
"Easy edit & source .vimrc
nmap <silent> <leader>ev :e $MYVIMRC<cr>
nmap <silent> <leader>sv :so $MYVIMRC<cr>
"For LaTeX background compilation
nmap <silent> <leader>pl :!pl<cr>
"Fast saving / sudo saving
nmap <leader>w :w!<cr>
cmap w!! w !sudo tee > /dev/null %
"Close buffer without loosing split
map <leader>q :bp\|bd #<cr>
"Easy windows switching
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
"Managing tabs
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tq :tabclose<cr>
"Moving through tabs
map <leader>n <esc>:tabprevious<CR>
map <leader>m <esc>:tabnext<CR>
"Moving through buffers
map <leader><Tab> <esc>:bnext<CR>
map <C-tab> <esc>:bprevious<CR>
"Just for wrapping text browsing
map j gj
map k gk
"Don't jump on *
nmap * *N
"Turn off lights
nmap <F8> :nohlsearch<CR>
"Markup signs
set listchars=tab:▸\ ,eol:¬
nmap <leader>l :set list!<CR>
"Sort alphabetically :)
vmap <Leader>s :sort<CR>
"Moving code blocks
vmap < <gv
vmap > >gv
"HEX MODE
map <leader>h :%!xxd<CR>
map <leader>r :%!xxd -r<CR>
"---Plugins---
"Git fugitive
nnoremap <leader>ga :Git add %:p<CR><CR>
nnoremap <leader>gb :Gblame<CR>
nnoremap <leader>gc :Gcommit -v<CR>
nnoremap <leader>gp :Git push origin &<CR>
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>gco :Git checkout<Space>
"CtrlP
nmap <leader>d :CtrlP ~/Dropbox<CR>
