# Auto-generated by canto because you don't have one.
# Please copy to/create ~/.canto/conf.py

from canto.extra import *

link_handler("chromium \"%u\"")
image_handler("feh \"%u\"", fetch=True)

add("http://habrahabr.ru/rss")

add("http://tech.onliner.by/feed")
add("http://auto.onliner.by/feed")
add("http://people.onliner.by/feed")
add("http://realt.onliner.by/feed")

colors[1] = 110

# filters=[show_unread]
keys['s'] = save

never_discard("unread")

filters=[show_unread, None]
