# Auto-generated by canto because you don't have one.
# Please copy to/create ~/.canto/conf.py

from canto.extra import *

link_handler("chromium \"%u\"")
link_handler("vlc \"%u\"", ext="mp3")
image_handler("feh \"%u\"", fetch=True)

add("http://habrahabr.ru/rss", rate=5, keep=300)
add("http://onliner.by/feed", rate=5, keep=300)
add("http://www.ixbt.com/export/articles.rss", rate=5, keep=300)
add("http://www.ixbt.com/export/hardnews.rss", rate=5, keep=300)
add("http://www.ixbt.com/export/softnews.rss", rate=5, keep=300)
add("http://www.opennet.ru/opennews/opennews_all_noadv.rss", rate=5, keep=300)

colors[0] = "green"
colors[1] = "yellow"
colors[2] = "red"
colors[3] = "white"
colors[4] = "magenta"
colors[6] = "cyan"

keys['s'] = save

never_discard("unread")

filters=[show_unread, None]
