[redshift]
temp-day=6000
temp-night=4400
transition=1
brightness-day=1
brightness-night=0.9
;gamma-day=1:1:1
;gamma-night=1:0.8:0.8
;location-provider=manual/geoclue/geoclue2
location-provider=manual
[manual]
lat=53.5072
lon=28.1522
;[randr]
;screen=0
